export const gradients = {
    indigo: ['#dcd6ff', '#b8adff', '#9285ff', '#7766ff', '#4833ff', '#3525db', '#261ab1', '#1a1093', '#10097a',],
    green: ['#dcfdc3', '#affc9d', '#7cf86c', '#4bf246', '#0cea1c', '#0dc928', '#0ca82f', '#038731', '#047031',],
    blue: ['#ccfffa', '#9afefe', '#66f1fc', '#41dffa', '#07c2f7', '#0497d4', '#0171b1', '#02518e', '#003a76',],
    yellow: ['#fff8db', '#fff0b8', '#ffe495', '#ffd97b', '#ffc84f', '#dba339', '#b78127', '#936118', '#7a4b10',],
    pink: ['#ffd8f2', '#ffb1ea', '#ff8aea', '#ff6df1', '#ff3dfe', '#cd2ddb', '#9d1fb7', '#731493', '#540b7a',],
}

export const baseRating = {
    "0": 2, "1": 5, "2": 4, "3": 1, "4": 3,
    "5": 2, "6": 4, "7": 1, "8": 5, "9": 3,
    "10": 2, "11": 4, "12": 1, "13": 3, "14": 5,
    "15": 2, "16": 4, "17": 1, "18": 3, "19": 5,
    "20": 2, "21": 4, "22": 1, "23": 3, "24": 5,
    "25": 3, "26": 4, "27": 2, "28": 1, "29": 2,
    "30": 4, "31": 1, "32": 3, "33": 5, "34": 2,
    "35": 4, "36": 1, "37": 5, "38": 3, "39": 2,
    "40": 5, "41": 4, "42": 1, "43": 3,
}

export const demoData = {
    "15": 2, "16": 4, "17": 1, "18": 3, "19":5, "20": 2, "21":4, "22": 1, "23": 3, "24":5, 
  }

  export const questionData= {
        "questions": [
          "What does happiness mean to you?",
          "What are your core values?",
          "How do you define success?",
          "What is the most important lesson you've learned in life?",
          "What is your biggest fear?",
          "What role does love play in your life?",
          "What are you most grateful for?",
          "How do you handle failure?",
          "What does it mean to live a good life?",
          "What motivates you to get up every day?",
          "What is your purpose in life?",
          "What makes you feel truly alive?",
          "How do you find peace in difficult times?",
          "What is your relationship with money?",
          "What is your greatest accomplishment?",
          "How do you define friendship?",
          "What are your dreams and aspirations?",
          "What do you want your legacy to be?",
          "What do you think happens after we die?",
          "How do you deal with uncertainty?",
          "What does freedom mean to you?",
          "How do you measure success?",
          "What is your philosophy on life?",
          "How do you maintain a work-life balance?",
          "What are your passions?",
          "What role does spirituality or religion play in your life?",
          "How do you manage stress?",
          "What is the meaning of life, in your opinion?",
          "How do you define love?",
          "What is the most important thing in your life right now?",
          "How do you cultivate positive relationships?",
          "What are your thoughts on destiny and free will?",
          "How do you stay true to yourself?",
          "What is your favorite way to spend time?",
          "What are the biggest challenges you've faced in life?",
          "What does it mean to be a good person?",
          "How do you cope with loss?",
          "What are your thoughts on aging?",
          "How do you find inspiration?",
          "What role does creativity play in your life?",
          "How do you stay motivated?",
          "What is your biggest regret?",
          "How do you make important decisions?",
          "What does kindness mean to you?",
          "How do you maintain a positive mindset?",
          "What are your thoughts on forgiveness?",
          "How do you deal with difficult emotions?",
          "What is your relationship with time?",
          "How do you practice self-care?",
          "What do you value most in life?",
          "What is your definition of beauty?",
          "How do you handle change?",
          "What does it mean to be authentic?",
          "How do you pursue your goals?",
          "What is your relationship with nature?",
          "How do you define happiness?",
          "What does it mean to live intentionally?",
          "How do you express gratitude?",
          "What role does family play in your life?",
          "How do you deal with failure?",
          "What is your favorite memory?",
          "How do you stay connected to others?",
          "What are your thoughts on happiness?",
          "How do you cultivate mindfulness?",
          "What does success look like to you?",
          "How do you manage your time?",
          "What is your relationship with technology?",
          "How do you handle conflict?",
          "What are your thoughts on materialism?",
          "How do you find meaning in your work?",
          "What does it mean to be resilient?",
          "How do you define self-love?",
          "What role does education play in your life?",
          "How do you maintain healthy boundaries?",
          "What are your thoughts on solitude?",
          "How do you handle criticism?",
          "What does it mean to be compassionate?",
          "How do you cultivate joy?",
          "What are your thoughts on ambition?",
          "How do you approach personal growth?",
          "What does it mean to be successful?",
          "How do you stay focused on your goals?",
          "What are your thoughts on sacrifice?",
          "How do you nurture your relationships?",
          "What role does honesty play in your life?",
          "How do you find balance in life?",
          "What are your thoughts on competition?",
          "How do you practice patience?",
          "What does it mean to be brave?",
          "How do you deal with disappointment?",
          "What are your thoughts on optimism?",
          "How do you find joy in the little things?",
          "What does it mean to be fulfilled?",
          "How do you stay true to your values?",
          "What role does community play in your life?",
          "How do you cultivate inner peace?",
          "What are your thoughts on generosity?",
          "How do you approach new experiences?",
          "What does it mean to live with purpose?",
          "How do you celebrate your successes?"
        ]    
  }